name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ManagementConsole/**'
      - 'SampleGame/**'
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - 'ManagementConsole/**'
      - 'SampleGame/**'
      - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Install Lambda dependencies
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          yarn
      - name: Build Management console
        run: yarn build-toolkit
      - name: Build Sample Game
        run: yarn build-sample-game
  savepr:
    runs-on: ubuntu-latest
    name: Save PR number if running on PR by dependabot
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Create Directory and save issue
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }}
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v4
        name: Upload artifact
        with:
          name: pr
          path: pr/
