name: Build Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/build-docs.yml'
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/build-docs.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: borales/actions-yarn@v2.3.0
      - name: Capture branch and tag
        id: branch_name
        run: |
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Build docs website
        run: yarn build-docs-website