name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ManagementConsole/**'
      - 'SampleGame/**'
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - 'ManagementConsole/**'
      - 'SampleGame/**'
      - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # test against latest update of each major .Net version, as well as specific updates of LTS versions:
        net: [3.1]
    name: .Net ${{ matrix.net }}
    env:
      DOTNET: ${{ matrix.net-version }}
      OS: ${{ matrix.os }}
      AWS_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.net }}
      - name: Build with dotnet
        run: dotnet build --configuration Release
  savepr:
    runs-on: ubuntu-latest
    name: Save PR number if running on PR by dependabot
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Create Directory and save issue
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }}
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        name: Updload artifact
        with:
          name: pr
          path: pr/
