name: Build

on:
  pull_request:
    branches:
      - master
    paths:
      - 'powertools-cloudformation/**'
      - 'powertools-core/**'
      - 'powertools-serialization/**'
      - 'powertools-logging/**'
      - 'powertools-sqs/**'
      - 'powertools-tracing/**'
      - 'powertools-validation/**'
      - 'powertools-idempotency/**'
      - 'powertools-parameters/**'
      - 'powertools-metrics/**'
      - 'powertools-test-suite/**'
      - 'pom.xml'
      - '.github/workflows/**'
  push:
    branches:
      - master
    paths:
      - 'powertools-cloudformation/**'
      - 'powertools-core/**'
      - 'powertools-serialization/**'
      - 'powertools-logging/**'
      - 'powertools-sqs/**'
      - 'powertools-tracing/**'
      - 'powertools-validation/**'
      - 'powertools-idempotency/**'
      - 'powertools-parameters/**'
      - 'powertools-metrics/**'
      - 'powertools-test-suite/**'
      - 'pom.xml'
      - '.github/workflows/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [8, 8.0.192, 11.0.x, 11.0.3, 12, 13, 15, 16, 17 ]
    name: Java ${{ matrix.java }}
    env:
      OS: ${{ matrix.os }}
      JAVA: ${{ matrix.java-version }}
      AWS_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -Pbuild-without-spotbugs -B package --file pom.xml
  savepr:
    runs-on: ubuntu-latest
    name: Save PR number if running on PR by dependabot
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Create Directory and save issue
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }}
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        name: Updload artifact
        with:
          name: pr
          path: pr/
